name: Verify Self
on: [ push, pull_request ]

env:
  BUNDLE_FILE: "dist/index.js"
  BUNDLE_COMMAND: "npm run bundle"

jobs:
  verify-latest:
    name: Verify Latest Bundle
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install
      run: npm ci

    - name: Verify Latest Bundle
      uses: ./
      with:
        bundle_file: ${{ env.BUNDLE_FILE }}
        bundle_command: ${{ env.BUNDLE_COMMAND }}

  verify-release:
    name: Verify Tagged Bundle
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install
      run: npm ci

    - name: Verify Tagged Bundle
      uses: tetchel/bundle-verifier@v1
      with:
        bundle_file: ${{ env.BUNDLE_FILE }}
        bundle_command: ${{ env.BUNDLE_COMMAND }}
